### ISSUE TITLE
SHC output labels

### ISSUE THREAD

**Issue by pkimes** [pkimes/sigclust2#1]
Package should include a function to determine the cluster labels based on significant splits.

**Comment by pkimes** [comment]
implemented now using `shcutree` function.

**Comment by alifarhat40** [comment]
Hi there,

I am getting the following error when trying to cut a tree:

```
cut<-shcutree(shc_obj,cluster_labels)
write.table(cut,'ecoli_shc_final_clusters.txt',row.names = F)
```

```
Error in shcutree(shc_obj, cluster_labels) : 
  length of cluster labels != n
```

This is what the tree looks like for reference. I set the p-value at 0.99999 because I just want to see the significance on the bottom leafs. I prefer SHC bottom-up instead of the implemented top-down. 
![image](https://github.com/pkimes/sigclust2/assets/32119344/b71e92d1-0915-42b4-ba4d-585f624046bc)
